# Travis CI script
# This is a skeleton created by zproject.
# You can add hand-written code here.

language: c

cache: ccache

os:
- linux

sudo: true

# Set CI_TIME=true to enable build-step profiling in Travis
# Set CI_TRACE=true to enable shell script tracing in Travis
# Set CI_CONFIG_QUIET=true to enable "configure --quiet" (only report stderr)
env:
  global:
    - CI_TIME=false
    - CI_TRACE=false
    - CI_CONFIG_QUIET=true

before_install:
- git clone git://github.com/zeromq/libzmq.git
- ( cd libzmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
- git clone git://github.com/zeromq/czmq.git
- ( cd czmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )

script:
- ./go/util/goinstall.sh --64
- source /home/travis/.bashrc
- go version
- cd go; make; cd -
- export CFLAGS="-ldl"
- ./autogen.sh 
- ./configure 
- make check
