# Travis CI script
# This is a skeleton created by zproject.
# You can add hand-written code here.

language: c

cache: ccache

os:
- linux

sudo: true

# Set CI_TIME=true to enable build-step profiling in Travis
# Set CI_TRACE=true to enable shell script tracing in Travis
# Set CI_CONFIG_QUIET=true to enable "configure --quiet" (only report stderr)
env:
  global:
    - CI_TIME=false
    - CI_TRACE=false
    - CI_CONFIG_QUIET=true

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_12.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_12.04/Release.key'
    packages:
    - libczmq-dev

script:
- ./go/util/goinstall.sh --64
- /home/travis/.go/bin/go version
- export GOROOT=/home/travis/.go 
- export GOPATH=/home/travis/.go
- cd go; /home/travis/.go/bin/go build -o libmockdiscgo.so -buildmode=c-shared libmockdiscgo.go; cd -
- export CFLAGS="-ldl"
- ./autogen.sh 
- ./configure 
- make check
